# Use postgres/example user/password credentials
version: '3.1'

services:

  teashop-db:
    image: postgres
    restart: always
    volumes:
      - teashop-data:/var/lib/postgresql/data
    ports:
      - 5432:5432   
    environment:
      POSTGRES_DB: teashop
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    restart: always
    depends_on:
      - teashop-db
    ports:
      - 8000:8080

volumes:
  teashop-data:
